// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FScenario")>]
[<assembly: AssemblyDescriptionAttribute("Reusable integration test building blocks to write integration tests in a more safe and fun way")>]
[<assembly: GuidAttribute("871111ca-f7e3-48c5-95b1-6eec4c289948")>]
[<assembly: AssemblyProductAttribute("FScenario")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FScenario"
    let [<Literal>] AssemblyDescription = "Reusable integration test building blocks to write integration tests in a more safe and fun way"
    let [<Literal>] Guid = "871111ca-f7e3-48c5-95b1-6eec4c289948"
    let [<Literal>] AssemblyProduct = "FScenario"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
