// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.InteropServices

[<assembly: AssemblyTitleAttribute("FScenario.Http")>]
[<assembly: AssemblyDescriptionAttribute("Reusable HTTP server integration test building blocks to write integration tests in a more safe and fun way")>]
[<assembly: GuidAttribute("871111ca-f7e3-48c5-95b1-6eec4c289949")>]
[<assembly: AssemblyProductAttribute("FScenario.Http")>]
[<assembly: AssemblyVersionAttribute("2.6.0")>]
[<assembly: AssemblyFileVersionAttribute("2.6.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FScenario.Http"
    let [<Literal>] AssemblyDescription = "Reusable HTTP server integration test building blocks to write integration tests in a more safe and fun way"
    let [<Literal>] Guid = "871111ca-f7e3-48c5-95b1-6eec4c289949"
    let [<Literal>] AssemblyProduct = "FScenario.Http"
    let [<Literal>] AssemblyVersion = "2.6.0"
    let [<Literal>] AssemblyFileVersion = "2.6.0"
